##########################################################################################################
#
#
#                                 ____      _             _     _ _
#                                |  _ \ ___| |_ __ _ _ __| |   (_) |__
#                                | |_) / _ \ __/ _` | '__| |   | | '_ \
#                                |  __/  __/ || (_| | |  | |___| | |_) |
#                                |_|   \___|\__\__,_|_|  |_____|_|_.__/
#
#
# Website: https://petarmc.com
# GitHub: https://github.com/PetarMc1/PetarLib-Bukkit
# License: MIT
# Made with ❤️ by Petar_mc
##########################################################################################################
config_version: 1

debug: false # Whether to enable debug mode for the plugin, which may provide additional logging and information for troubleshooting.
defaultMaxRetries: 3 # Default maximum number of retries for failed operations for the HTTP client.
